site_name: Docker Swarm Rocks
site_description: Docker Swarm mode ideas and tools

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'indigo'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: tiangolo/dockerswarm.rocks
repo_url: https://github.com/tiangolo/dockerswarm.rocks
edit_uri: ""
google_analytics:
    - 'UA-133194648-1'
    - 'auto'

nav:
    - Docker Swarm Rocks: index.md
    - Traefik Proxy with HTTPS: traefik.md
    - Traefik Proxy with HTTPS - Technical Details: traefik-technical-details.md
    - Traefik Proxy with HTTPS using volume (outdated): traefik-with-volume.md
    - Swarmprom for real-time monitoring and alerts: swarmprom.md
    - Swarmpit web user interface for your Docker Swarm cluster: swarmpit.md
    - Portainer web user interface for your Docker Swarm cluster: portainer.md
    - The Lounge - self-hosted web IRC client: thelounge.md
    - GitLab CI runner for CI/CD: gitlab-ci.md
    - Project Generators: project-generators.md
    - Release Notes: release-notes.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
